In [1]:
import numpy as np

In [13]:
#reshape refers to the same underlying array
a = np.arange(6).reshape(2,3)
print(a)
b = a.reshape(3,2)
print(b)
a[1,1] = 50
print(a)
print(b)

In [8]:
#slicing lists makes a copy...
a = range(10)
b = a[:5]
b[2]=50
print(a)
print(b)

In [12]:
#but slicing numpy arrays does not
a = np.arange(10)
b = a[:5]
b[2]=50
print(a)
print(b)

[ 0  1 50  3  4  5  6  7  8  9]
[ 0  1 50  3  4]


In [20]:
#however saving the result of a slice
#to another slice works as you would expect
a = np.arange(10)
b = np.zeros(10)
c = np.zeros(10)

b = a[:5]
c[:5] = a[:5]
a[4] = 50
print(a)
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[ 0  1  2  3 50  5  6  7  8  9]
[ 0  1  2  3 50]
[ 0.  1.  2.  3.  4.  0.  0.  0.  0.  0.]
4420609648
4420610688
4420610768


In [24]:
import time
def timeMe(func):
    start = time.time();
    func()
    end = time.time();
    print("took",str(end-start))

In [25]:
#time of in-place (no copy) versus an op that makes a copy
def f1():
    a = np.arange(1000)
    a = a*2

def f2():
    a = np.arange(1000)
    a*=2;

timeMe(f1)
timeMe(f2)

('took', '2.31266021729e-05')
('took', '7.15255737305e-06')


In [32]:
#broadcasting
a = np.arange(25).reshape((5,5))
b = np.arange(5)
print(a)
print(b)
c = b[None,:]
print(a*b[None,:])
print(a*b[None,:])
print(a*b[:,None])

c = np.expand_dims(b, axis=0)
print(id(c))
print(id(b))
b[0]=50
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4]
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]
 [ 0 16 34 54 76]
 [ 0 21 44 69 96]]
[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]
 [45 48 51 54 57]
 [80 84 88 92 96]]
4420611008
4420611728
[50  1  2  3  4]
[[50  1  2  3  4]]


In [33]:
#broadcasting doesn't work with anything expect 1's...
a = np.arange(12).reshape((4,3))
b = np.arange(6).reshape((2,3))

print(a)
print(b)
print(a*b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [3 4 5]]


ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [34]:
#Vectorise any function!!
def myfunc(a,b):
    return a*(b) + 1

myufunc = np.vectorize(myfunc)

a = np.arange(9).reshape((3,3))
b = np.arange(3)

print(myufunc(a,b[None,:]))
print(myufunc(a,b[:,None]))

[[ 1  2  5]
 [ 1  5 11]
 [ 1  8 17]]
[[ 1  1  1]
 [ 4  5  6]
 [13 15 17]]


In [39]:
#fancy indexing

A = np.arange(27).reshape((3,3,3))

print(A)
#Desired end result:
# [ A[0,0,0] A[1,1,1]
#   A[2,2,2] A[0,0,2]]
fancyIndex = [
    np.array([  [0,1]
               ,[2,0]])
    ,np.array([ [0,1]
               ,[2,0]])
    ,np.array([ [0,1]
               ,[2,2]])
]

A[fancyIndex]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 0, 13],
       [26,  2]])